export enum ErrorCode {
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DEVICE_ALREADY_EXISTS = 'DEVICE_ALREADY_EXISTS',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DEVICE_ALREADY_REGISTERED = 'DEVICE_ALREADY_REGISTERED',
}
